### ISSUE TITLE
Buildbot doesn't seem to highlight runs with some failed tests in red

### ISSUE THREAD

**Issue by vaughnbetz** [fullmonte-for-PDT/fullmonte-source-code#17]
See the Nov. 20 run; it is green but some sub-tests have failed on specific builds (not on all builds). Maybe the Run_ctest.sh return code isn't set properly or some other communication problem from Run_ctest.sh to the buildbot scripts?

**Comment by yasmin-afsharnejad** [comment]
Added exit code detection to Run_ctest.sh script
