### ISSUE TITLE
Failing regression tests in buildbot runs

### ISSUE THREAD

**Issue by vaughnbetz** [fullmonte-for-PDT/fullmonte-source-code#3]
5 of the regression tests that should work according to Siyun are not passing; these should be debugged and fixed.
Several other regtests have known issues (see Siyun's wiki); these known failures should be commented out / temporarily removed from the buildbot runs and an issue on each should be filed to the person expected to fix or obselete the test (Jeff for those ones I believe).

**Comment by yasmin-afsharnejad** [comment]
Failing tests with known issues are commented.

**Comment by yasmin-afsharnejad** [comment]
I will work on Tests that are supposed to pass, but are now failing. They are temporarily commented from running tests.
